name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (UTC)

jobs:
  sync:
    name: Sync ğŸ”„
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: config git user info ğŸ”‘
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions[bot]"
      - name: Fetch upstream changes and Merge ğŸ”„
        id: fetch-changes
        run: |
          git remote add upstream https://github.com/pallets/flask.git
          git fetch upstream
          git merge upstream/2.1.x -m "Merge upstream changes into 'main' by GitHub Actions"
          git diff --name-only origin/main HEAD | grep -q -e '^docs/' # Check if docs changed
      - name: install dependencies ğŸ“¦
        run: |
          pip install -r requirements/docs.txt
          pip install PyGithub
          pip install -e .
      - name: Generate Translation Files ğŸ“š
        run: |
          cd docs
          make gettext
          sphinx-intl update -p _build/gettext
          cd ..
          git add docs/
          git commit -m "Update po files by GitHub Actions"
      - name: Push changes to GitHub ğŸš€
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue on GitHub ğŸ“
        run: python .github/workflows/create_issue.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
