name: Test Docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**/**.po
  pull_request:
    branches:
      - main
    paths:
      - docs/**/**.po
jobs:
  tests:
    name: Run tests ğŸ¤–
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Set up Python 3 ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"
      - name: Update PIP âœ¨
        run: |
          pip install -U wheel setuptools pip
      - name: Install tox ğŸ“¦
        run: pip install tox
      - name: Run tests ğŸš€
        run: tox -e docs
